### ISSUE TITLE
Error: loop or previous error loading module

### ISSUE THREAD

**Issue by ofirmc** [pkulchenko/MobDebug#81] opened 2022-11-23 09:11 UTC
I'm trying to remote debug a server that has an open port: 3254.
On that server I use listen() like this:  require("mobdebug").listen("*", 3254)
Port 3254 also receives https request e.g. in the browser we use https://<server_IP>:3254 to browse to the web site.
When browsing to a page that eventually runs a LUA code that has require("mobdebug").listen("*", 3254), I get the following error:
"loop or previous error loading module..."
Do you know what could cause the error?

**Comment by pkulchenko** [comment] 2022-11-30 05:36
Do you by any chance have "mobdebug.lua" file in one of the project folders (or maybe socket.lua)? Is there a detailed stack trace that would point to line numbers where the error may be happening?

**Comment by pkulchenko** [comment] 2023-06-24 21:20
Closing, as I can't reproduce it and it doesn't seem to be an issue with the library.

**Closed by pkulchenko** 2023-06-24 21:20 UTC
